---
- name: Deploy Docker Stack with Auto-TLS
  hosts: all
  become: yes
  vars_files:
    - secrets.yml

  tasks:
    - name: Ensure SSL certs directory exists
      file:
        path: /home/certs
        state: directory
        mode: 0755

    - name: Generate default SSL certs (fallback)
      command: >
        openssl req -x509 -newkey rsa:4096 -keyout /home/certs/key.pem -out /home/certs/cert.pem
        -days 365 -nodes -subj "/CN=*"
      args:
        creates: /home/certs/cert.pem

    - name: Install system dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install Python requirements
      pip:
        name:
          - "docker==5.0.3"
          - "docker-compose==1.29.2"
          - "urllib3==1.26.6"
          - "chardet==3.0.4"
          - "requests==2.25.1"
        state: present
        extra_args: --force-reinstall

    - name: Copy nginx.conf
      copy:
        src: ./nginx.conf
        dest: /home/nginx.conf
        mode: 0644
    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml.j2
        dest: /home/docker-compose.yml
        mode: 0644
      
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 wordpress.cloud-1 phpmyadmin.cloud-1"
        state: present
    
    - name: Deploy docker-compose stack
      community.docker.docker_compose:
        project_src: /home/
        build: yes
        restarted: yes
        recreate: always
        remove_orphans: yes